### PR TITLE
converted to swift 3

### PR DESCRIPTION
**Pull request by szehnder**
this was the automatic conversion to swift 3 when I opened the project in Xcode 8 today.  builds fine in Xcode.

### CODE REVIEW

**Comment by ened** [comment]
@andysmart Any chance to merge?

**Review by rrallo — APPROVED** [review]
These changes work fine with swift 3.0 for me. I think we should merge these in :)

**Comment by rrallo** [comment]
@szehnder fork?

**Comment by andysmart** [comment]
Sorry guys - I'll review and merge this tonight. This is great work. I'm sure you all think this has been abandoned which is the last thing I want.

**Comment by ened** [comment]
@andysmart, any update please?

**Comment by andysmart** [comment]
This is great work, thanks @szehnder. There's a couple of last issues with this fork, but I'm going to merge and fix here rather than re-run the migrator.

- Example project no longer compiles, and needs Swift 3.0 conversion
- `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` is now required to get the project to run correctly

**Comment by andysmart** [comment]
Alright, tweaked and tagged as v0.0.3. Thanks folks

**Pull request merged**
